#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Remove historically mis-pushed build artifacts from the remote repo.

Deletion is done the Git way: create a tree on top of the current remote tree
with the unwanted paths set to sha=null, then commit + move the ref forward.
Nothing is force-pushed and history still contains the blobs (recoverable).

Usage:
  python gh_cleanup_remote.py --dry-run
  python gh_cleanup_remote.py
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gh_diff_preview import api, read_token, OWNER, REPO, BRANCH  # noqa: E402

# mis-pushed build output (bin-v18) -- prefix match on remote path
TARGET_PREFIXES = [
    "tools/tiaportal-mcp/src/TiaMcpServer/bin-v18/",
]

COMMIT_MSG = """chore: remove mis-pushed build artifacts (bin-v18) and add .gitignore

Removes ~13.5 MB of build output that was accidentally committed earlier:
compiled binaries (TiaMcpServer.exe, 57 dependency DLLs), debug symbols
(.pdb) and a startup log under
tools/tiaportal-mcp/src/TiaMcpServer/bin-v18/Release/net48/.

These are regenerated by `dotnet build` and must never live in the repo.
A .gitignore is added to prevent bin*/obj*/BAK snapshots from being
committed again.

Deletion is a normal forward commit: history still contains the blobs, so
nothing is lost. Not a force push.
"""

# Appended to the existing .gitignore (never overwrites it).
# These are exactly the gaps that let bin-v18/ and SRC-BAK snapshots in.
GITIGNORE_ADDITION = """
# --- 2026-08-31: close the gaps that let build output / backups in ---
# NOTE: previous rules only covered bin/Release and bin-v20/Release,
# so bin-v18/Release (13.5 MB) slipped through. Cover every variant.
**/bin-v*/
**/bin-verify*/
**/obj-v18/
**/obj-verify*/

# Backup snapshots: previous rule was *.bak_* (underscore) and missed
# the hyphen forms actually used here (SRC-BAK-20260730, .BAK-20260819).
**/SRC-BAK-*/
**/*.BAK-*/
**/*.bak-*/
**/*.BAK*/
**/*.bak*/

# Python tooling / IDE
__pycache__/
*.pyc
.vscode/
.idea/

# Generated push tooling state
gh_push_plan.json
"""


def main():
    dry = "--dry-run" in sys.argv
    token = read_token()
    if not token:
        print("ERROR: no token")
        return 2

    ref = api("/repos/%s/%s/git/ref/heads/%s" % (OWNER, REPO, BRANCH), token)
    head = ref["object"]["sha"]
    commit = api("/repos/%s/%s/git/commits/%s" % (OWNER, REPO, head), token)
    base_tree = commit["tree"]["sha"]
    print("Remote HEAD: %s" % head)
    print("Base tree  : %s" % base_tree)

    tree = api("/repos/%s/%s/git/trees/%s?recursive=1" % (OWNER, REPO, BRANCH), token)
    all_blobs = [i for i in tree.get("tree", []) if i.get("type") == "blob"]
    print("Remote blobs before: %d" % len(all_blobs))

    doomed = [i for i in all_blobs
              if any(i["path"].startswith(p) for p in TARGET_PREFIXES)]
    total = sum(i.get("size", 0) for i in doomed)
    print("\nTo delete: %d files, %.2f MB" % (len(doomed), total / 1048576.0))
    for i in doomed[:10]:
        print("   - %s (%d)" % (i["path"], i.get("size", 0)))
    if len(doomed) > 10:
        print("   ... and %d more" % (len(doomed) - 10))

    if not doomed:
        print("Nothing to delete.")
        return 0

    # deletion entries: sha=null
    entries = [{"path": i["path"], "mode": "100644", "type": "blob", "sha": None}
               for i in doomed]

    # add .gitignore so this cannot happen again
    import base64
    gi_path = ".gitignore"
    existing = ""
    for i in all_blobs:
        if i["path"] == gi_path:
            gb = api("/repos/%s/%s/contents/%s?ref=%s" % (OWNER, REPO, gi_path, head), token)
            existing = base64.b64decode(gb["content"]).decode("utf-8", errors="replace")
            break
    merged = existing.rstrip("\n") + "\n" + GITIGNORE_ADDITION
    blob = api("/repos/%s/%s/git/blobs" % (OWNER, REPO), token, method="POST",
               payload={"content": base64.b64encode(merged.encode("utf-8")).decode("ascii"),
                        "encoding": "base64"})
    entries.append({"path": gi_path, "mode": "100644", "type": "blob", "sha": blob["sha"]})
    print("\n+ .gitignore updated: %d -> %d bytes (merged, nothing overwritten)"
          % (len(existing), len(merged)))

    if dry:
        print("\n--dry-run: nothing changed remotely.")
        return 0

    new_tree = api("/repos/%s/%s/git/trees" % (OWNER, REPO), token, method="POST",
                   payload={"base_tree": base_tree, "tree": entries})
    print("\nNew tree: %s" % new_tree["sha"])

    new_commit = api("/repos/%s/%s/git/commits" % (OWNER, REPO), token, method="POST",
                     payload={"message": COMMIT_MSG, "tree": new_tree["sha"], "parents": [head]})
    print("New commit: %s" % new_commit["sha"])

    api("/repos/%s/%s/git/refs/heads/%s" % (OWNER, REPO, BRANCH), token, method="PATCH",
        payload={"sha": new_commit["sha"]})

    # verify
    tree2 = api("/repos/%s/%s/git/trees/%s?recursive=1" % (OWNER, REPO, BRANCH), token)
    after = [i for i in tree2.get("tree", []) if i.get("type") == "blob"]
    left = [i for i in after if any(i["path"].startswith(p) for p in TARGET_PREFIXES)]
    ref2 = api("/repos/%s/%s/git/ref/heads/%s" % (OWNER, REPO, BRANCH), token)
    print("\nVERIFY")
    print("  ref == new commit          : %s" % (ref2["object"]["sha"] == new_commit["sha"]))
    print("  bin-v18 files remaining    : %d (want 0)" % len(left))
    print("  blob count %d -> %d" % (len(all_blobs), len(after)))
    print("  https://github.com/%s/%s/commit/%s" % (OWNER, REPO, new_commit["sha"]))
    return 0 if not left else 5


if __name__ == "__main__":
    sys.exit(main())
