#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
GitHub <-> local diff preview (READ ONLY, no push).

Compares the remote repo tree (Git Database API, recursive) against the local
work tree using git blob SHA1, and prints:
  ADDED    - local only
  MODIFIED - same path, different blob sha
  DELETED  - remote only (listed, never auto-removed)
  SAME     - identical (excluded from push)

Exclusion rules (house rules): BAK/bak backup dirs, bin*/obj* build output,
*.log, binaries (dll/exe/pdb), and other noise.

Usage: python gh_diff_preview.py [--token TOKEN]
"""
import hashlib
import json
import os
import re
import ssl
import sys
import urllib.error
import urllib.request

OWNER = "1748477582"
REPO = "tia-portal-openness-mcp-v18"
BRANCH = "master"

# local root -> remote prefix inside the repo
LOCAL_ROOT = r"C:/Users/106905/Downloads/TIA_MCP_V18_Work/TIA_MCP_Delivery_v2.3.0_20260704/tools/tiaportal-mcp"
REMOTE_PREFIX = "tools/tiaportal-mcp"

# --- exclusions (case-insensitive matching on the relative path) ---
EXCLUDE_DIR_RE = re.compile(
    r"(^|/)("
    r"\.git|\.vs|\.vscode|__pycache__|node_modules|packages|TestResults|"
    # build output: 'bin', 'bin-v18', 'bin-verify18', 'bin-v18.BAK-...' etc.
    r"bin(/|$)|bin[-.][\w.\-]*(/|$)|"
    r"obj[\w.\-]*(/|$)|"
    # source/backup snapshots: 'SRC-BAK-20260730', '.BAK-20260819', '.bak-20260821'
    r"[\w.\-]*[.\-]BAK[\w.\-]*(/|$)|BAK[\w.\-]*(/|$)"
    r")",
    re.IGNORECASE,
)
EXCLUDE_FILE_RE = re.compile(
    r"\.("
    r"log|dll|exe|pdb|zip|7z|zap\d*|apk|cache|tmp|bak|"
    r"user|suo|userprefs|nupkg|snk|dSYM"
    r")$",
    re.IGNORECASE,
)

# files that must never be pushed even if they show as changed
EXCLUDE_BASENAMES = {
    "launchSettings.json",
    ".DS_Store",
    "Thumbs.db",
    "gh_push_plan.json",  # generated by this script
}


def read_token():
    if len(sys.argv) > 2 and sys.argv[1] == "--token":
        return sys.argv[2]
    # Prefer the user's consolidated key file (never echo the value).
    key_file = r"D:/Users/Desktop/APIkey.json"
    if os.path.exists(key_file):
        raw = open(key_file, "rb").read().decode("utf-8-sig", errors="replace")
        for line in raw.splitlines():
            if "github" in line.lower():
                parts = re.split(r"[：:]", line, maxsplit=1)
                if len(parts) == 2:
                    tok = parts[1].strip().strip('"').strip("'").strip()
                    if tok:
                        return tok
    env = os.environ.get("GITHUB_TOKEN") or os.environ.get("GH_TOKEN")
    if env:
        return env.strip()
    return None


def api(path, token, method="GET", payload=None):
    url = "https://api.github.com" + path
    data = None
    if payload is not None:
        data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(url, data=data, method=method)
    req.add_header("Authorization", "Bearer " + token)
    req.add_header("Accept", "application/vnd.github+json")
    req.add_header("X-GitHub-Api-Version", "2022-11-28")
    req.add_header("User-Agent", "tia-mcp-push-script")
    if data:
        req.add_header("Content-Type", "application/json")
    ctx = ssl.create_default_context()
    try:
        with urllib.request.urlopen(req, timeout=60, context=ctx) as r:
            body = r.read().decode("utf-8")
            return json.loads(body) if body else {}
    except urllib.error.HTTPError as e:
        body = e.read().decode("utf-8", errors="replace")
        raise RuntimeError("HTTP %s on %s: %s" % (e.code, path, body[:400]))


def git_blob_sha(data: bytes) -> str:
    h = hashlib.sha1()
    h.update(b"blob %d\0" % len(data))
    h.update(data)
    return h.hexdigest()


def should_exclude_rel(rel: str) -> bool:
    if EXCLUDE_DIR_RE.search(rel):
        return True
    base = os.path.basename(rel)
    if EXCLUDE_FILE_RE.search(base):
        return True
    if base in EXCLUDE_BASENAMES:
        return True
    return False


def local_files():
    out = {}
    root = os.path.abspath(LOCAL_ROOT)
    for dirpath, dirnames, filenames in os.walk(root):
        # prune excluded dirs in-place
        dirnames[:] = [
            d
            for d in dirnames
            if not EXCLUDE_DIR_RE.search(
                os.path.relpath(os.path.join(dirpath, d), root).replace("\\", "/") + "/"
            )
        ]
        for fn in filenames:
            full = os.path.join(dirpath, fn)
            rel = os.path.relpath(full, root).replace("\\", "/")
            if should_exclude_rel(rel):
                continue
            try:
                with open(full, "rb") as f:
                    data = f.read()
            except Exception as e:
                print("  [skip-unreadable] %s (%s)" % (rel, e))
                continue
            out[rel] = (git_blob_sha(data), len(data))
    return out


def main():
    token = read_token()
    if not token:
        print("ERROR: no GitHub token found")
        return 2

    print("Remote: %s/%s @ %s" % (OWNER, REPO, BRANCH))
    ref = api("/repos/%s/%s/git/ref/heads/%s" % (OWNER, REPO, BRANCH), token)
    head_sha = ref["object"]["sha"]
    print("HEAD commit: %s" % head_sha)

    tree = api(
        "/repos/%s/%s/git/trees/%s?recursive=1" % (OWNER, REPO, BRANCH), token
    )
    remote = {}
    truncated = tree.get("truncated", False)
    for item in tree.get("tree", []):
        if item.get("type") == "blob":
            remote[item["path"]] = item["sha"]
    print("Remote blobs: %d (truncated=%s)" % (len(remote), truncated))

    print("Scanning local tree: %s" % LOCAL_ROOT)
    loc = local_files()
    print("Local files (after exclusions): %d" % len(loc))

    added, modified, same = [], [], []
    for rel, (sha, size) in sorted(loc.items()):
        rpath = "%s/%s" % (REMOTE_PREFIX, rel)
        if rpath not in remote:
            added.append((rel, rpath, size))
        elif remote[rpath] != sha:
            modified.append((rel, rpath, size, remote[rpath][:8], sha[:8]))
        else:
            same.append(rel)

    # remote-only files that fall under our prefix (candidates for deletion)
    deleted = []
    pref = REMOTE_PREFIX + "/"
    for rpath in sorted(remote):
        if rpath.startswith(pref):
            rel = rpath[len(pref) :]
            if rel not in loc and not should_exclude_rel(rel):
                deleted.append(rel)

    print()
    print("=" * 72)
    print("ADDED    (%d) - local only" % len(added))
    print("=" * 72)
    for rel, rpath, size in added:
        print("  + %s  (%d bytes)" % (rel, size))

    print()
    print("=" * 72)
    print("MODIFIED (%d) - content differs" % len(modified))
    print("=" * 72)
    for rel, rpath, size, rsha, lsha in modified:
        print("  ~ %s  (%d bytes, %s -> %s)" % (rel, size, rsha, lsha))

    print()
    print("=" * 72)
    print("DELETED  (%d) - remote only (NOT auto-removed)" % len(deleted))
    print("=" * 72)
    for rel in deleted[:50]:
        print("  - %s" % rel)
    if len(deleted) > 50:
        print("  ... and %d more" % (len(deleted) - 50))

    print()
    print("SUMMARY: added=%d modified=%d deleted=%d unchanged=%d" % (len(added), len(modified), len(deleted), len(same)))

    # persist for the push step
    plan = {
        "head_sha": head_sha,
        "added": [a[0] for a in added],
        "modified": [m[0] for m in modified],
        "deleted": deleted,
        "unchanged": len(same),
        "remote_prefix": REMOTE_PREFIX,
        "local_root": LOCAL_ROOT,
    }
    with open(os.path.join(LOCAL_ROOT, "gh_push_plan.json"), "w", encoding="utf-8") as f:
        json.dump(plan, f, indent=2, ensure_ascii=False)
    print("Plan written to gh_push_plan.json")
    return 0


if __name__ == "__main__":
    sys.exit(main())
